### ISSUE TITLE
[BUG] CSV Datasource error

### ISSUE THREAD

**Issue by bonacciog** [maiot-io/zenml#13]
**Describe the bug**
I'm not able to getting started with quickstart example pipeline.
Trying to run:
ds = CSVDatasource(name='Pima Indians Diabetes Dataset', path='gs://zenml_quickstart/diabetes.csv')

**To Reproduce**
I have followed QuickStart steps:
1. pip install zenml
2. zenml init
3. Run the QuickStart example

**Screenshots**
<img width="852" alt="Schermata 2021-01-15 alle 14 56 56" src="https://user-images.githubusercontent.com/45511179/104735539-fe8bd600-5741-11eb-98ac-44f5a0e5832a.png">

**Stack Trace**
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-10-dc93b347d532> in <module>
      1 # Add a datasource. This will automatically track and version it.
----> 2 ds = CSVDatasource(name='Pima Indians Diabetes Dataset', path='gs://zenml_quickstart/diabetes.csv')
      3 training_pipeline.add_datasource(ds)

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/zenml/core/datasources/csv_datasource.py in __init__(self, name, path, schema, **unused_kwargs)
     45             schema (str): optional schema for data to conform to.
     46         """
---> 47         super().__init__(name, schema, **unused_kwargs)
     48         self.path = path
     49 

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/zenml/core/datasources/base_datasource.py in __init__(self, name, schema, _id, _source, *args, **kwargs)
     61         else:
     62             # If none, then this is assumed to be 'new'. Check dupes.
---> 63             all_names = Repository.get_instance().get_datasource_names()
     64             if any(d == name for d in all_names):
     65                 raise Exception(

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/zenml/core/repo/repo.py in get_datasource_names(self)
    236             c = yaml_utils.read_yaml(file_path)
    237             n.append(c[keys.GlobalKeys.DATASOURCE][keys.DatasourceKeys.NAME])
--> 238         return list(set(n))
    239 
    240     @track(event=GET_DATASOURCES)

KeyError: 'datasource'

** Context (please complete the following information):**
 - OS: MacOS Big Sur 11.1
 - Python Version: 3.8.2
 - ZenML Version: 0.1.3

**Comment by hamzamaiot** [comment]
Thanks for reporting @bonacciog ! Could you please verify that your `pipelines_dir` does not contain any YAML files from older runs of ZenML. This might be due to a non-backwards compatible upgrade of the YAML standard from 0.1.2 to 0.1.3

**Comment by bonacciog** [comment]
@hamzamaiot Thanks for your reply!

<img width="568" alt="Schermata 2021-01-15 alle 15 08 40" src="https://user-images.githubusercontent.com/45511179/104736680-9b02a800-5743-11eb-929a-772b6c7e185e.png">

It does't seem there is an YAML file. Is this screenshot enough?

**Comment by hamzamaiot** [comment]
Could you check in the `pipelines` directory?

```
ls pipelines/
```

**Comment by bonacciog** [comment]
<img width="517" alt="Schermata 2021-01-15 alle 15 32 31" src="https://user-images.githubusercontent.com/45511179/104739368-e9fe0c80-5746-11eb-9d5b-be03f8a0e818.png">

**Comment by hamzamaiot** [comment]
ah yes, I see the bug. The `Untitle.ipynb` file should not exist in the `pipelines` directory. Actually, nothing should exist in the `pipelines` directory except the pipeline YAML configurations -> Thats a condition we should be catching in the code so thanks for bringing it up!

Your immediate solution would be to move the `Untitled.ipynb` out into the `root` and try again. It should hopefully work. 

P.S. If you wanted a recommended directory structure, we have one in our [docs](https://docs.zenml.io/repository/what-is-a-repository.html#recommended-repository-structure) for reference.  Hope it helps!

**Comment by bonacciog** [comment]
Thank you for your help @hamzamaiot!

I have created that file, so my mistake.
Now the dir is organized in this way:
<img width="569" alt="Schermata 2021-01-15 alle 16 35 38" src="https://user-images.githubusercontent.com/45511179/104746568-bd9abe00-574f-11eb-95fa-49fef3b6b435.png">

I have created the dir "notebooks" and file QuickStart.ipynb to start with QuickStart example.

Now I got another error:
<img width="1047" alt="Schermata 2021-01-15 alle 16 38 05" src="https://user-images.githubusercontent.com/45511179/104746852-1b2f0a80-5750-11eb-969b-edb9d36a5c74.png">

**Comment by bonacciog** [comment]
Maybe I have to work outside of subdirectories (notebooks, pipelines..) ? @hamzamaiot

**Comment by htahir1** [comment]
Sorry switching accounts. Now the error is clearer - the datasource already exists so you can either fetch it in your script using the `repository.get_datasource_by_name()` . The repository instance can be fetched by using `Repository.get_instance()` .

Or to start from scratch just delete the `pipelines` directory and it will work 👍

**Comment by bonacciog** [comment]
Thank you! @htahir1 
Now it is working fine! My mistake, sorry

**Comment by htahir1** [comment]
No problem! We also added a fix to the YAML pipelines dir problem you were facing in https://github.com/maiot-io/zenml/pull/14 . Thanks for the heads-up!
