### ISSUE TITLE
Main branch has dependency listed as <3.9 for python, which breaks on Arch which calls it 3.9.0

### ISSUE THREAD

**Issue by birdiesanders** [maiot-io/zenml#5]
A minor tweak to the deps should fix it up.

**Comment by birdiesanders** [comment]
Scratch that, I just noticed you aren't supporting 3.9 yet. A bummer, as I was really wanting to use this on my local machine because it has a real-man GPU in it.

**Comment by hamzamaiot** [comment]
> Scratch that, I just noticed you aren't supporting 3.9 yet. A bummer, as I was really wanting to use this on my local machine because it has a real-man GPU in it.

Thanks for fix. Regarding Python 3.9.0, some of the dependencies we have do not support it currently. We are working hard to support it soon. Is it possible for you to use the GPU in the meanwhile using <3.9.0?

**Comment by hamzamaiot** [comment]
@birdiesanders I opened up the Discussions tab on GitHub so we can have that discussion on the forum, rather than the issue board. Feel free to open up the Python 3.9 topic on there if you're still interested!
