### ISSUE TITLE
quickstart demo

### ISSUE THREAD

**Issue by SaraKingGH** [maiot-io/zenml#51]
I just found a small bug in the readme here: https://github.com/maiot-io/zenml/tree/main/examples/quickstart. we should have python quickstart.py instead of run.py.

**Comment by htahir1** [comment]
Makes sense, will fix!

**Comment by htahir1** [comment]
Fixed in f05be5e93e56b3d6f5e1b942b2aa551778b35590 . Thanks @SaraKingGH !
