### ISSUE TITLE
[BUG] Links in the Readme are not working

### ISSUE THREAD

**Issue by ramitsurana** [maiot-io/zenml#77]
**Describe the bug**
The [Readme file](https://github.com/maiot-io/zenml/blob/main/README.md) contains some outdated links for documentation at https://docs.zenml.io/.

**To Reproduce**
Please check the hyperlinks under [ZenML Paragraph](https://github.com/maiot-io/zenml/blob/main/README.md#what-is-zenml).

**Expected behavior**
It should point to the valid documentation pages.

**Comment by hamzamaiot** [comment]
Thank you @ramitsurana for pointing this out - @TremaMiguel PR fixes this, so ill close the issue
