### ISSUE TITLE
Not able to install zenml on Mojave or Ubuntu

### ISSUE THREAD

**Issue by batlogs** [maiot-io/zenml#81]
I am trying to install zenml on Mojave but I get the below error. I also did try to do the same on EC2 instance but still got an error

`pip install zenml` is the command I use to install

EC2 Python details

- Python - 3.5.2
- PIP - 20.3.4
- Error `ERROR: Could not find a version that satisfies the requirement tfx==0.25.0 (from zenml)
ERROR: No matching distribution found for tfx==0.25.0`

Mojave Python details

- Python - 3.9.1
- PIP - 21.0.1
- Error ` ERROR: Cannot install zenml==0.1.0 and zenml==0.1.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    zenml 0.1.1 depends on tfx==0.25.0
    zenml 0.1.0 depends on tfx==0.25.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies `

**Comment by htahir1** [comment]
What version of pip are you using? Can you upgrade it? It looks like you have an older version of pip? Or maybe you are using python 2 pip and not python 3 pip?

**Comment by htahir1** [comment]
This is super strange on closer inspection. Even the error message is strange as the conflict does not look like a conflict. Could you try doing `pip install zenml==0.3.7` ?

**Comment by batlogs** [comment]
I get the below error with the above command
`Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement zenml==0.3.7
ERROR: No matching distribution found for zenml==0.3.7`

**Comment by hamzamaiot** [comment]
Ah just noticed you are using Python 3.9.1. We do not currently support that - Please try using a VM with Python <3.9 >=3.6

**Comment by batlogs** [comment]
But I am getting this error in my EC2 instance. where Python = 3.5.2

**Comment by htahir1** [comment]
Can you please come over to the slack so we can discuss it in more detail quickly  and then we can summarize here? zenml.io/slack-invite

**Comment by batlogs** [comment]
I am on slack

**Comment by batlogs** [comment]
Is there a channel or just on general channel?

**Comment by htahir1** [comment]
Issue is resolved by using Python version > 3.6 and <=3.9!
