### ISSUE TITLE
[BUG] Unable to see pipelines for comparison (compare_training_runs() module) upon passing pipeline_name parameter to TrainingPipeline()

### ISSUE THREAD

**Issue by aak7912** [maiot-io/zenml#84]
**Describe the bug**
I created two pipelines and specified their names by passing pipeline_name parameter to  TrainingPipeline(). I was unable to see the pipelines listed on the comparison webpage (screenshot attached).

Next I created two pipelines without specifying the pipeline name and was able to see both those pipelines listed on comparison webpage

![image](https://user-images.githubusercontent.com/74846270/117586994-7fdfed80-b0d0-11eb-9026-b40868f74495.png)

**Comment by htahir1** [comment]
I am unable to reproduce this behavior. As discussed on Slack, will close issue
